name: Run runner
run-name: ${{ inputs.name }}

on:
  workflow_dispatch:
    inputs:
      endpoint:
        required: true
        type: string
        description: WebSocket endpoint
      os:
        required: true
        type: string
        description: The OS to run on
      name:
        required: false
        type: string
        description: The run name
        default: Run runner

jobs:
  censor:
    runs-on: ubuntu-latest
    steps:
      - name: Censor endpoint
        run: |
          ENDPOINT=$(jq -r '.inputs.endpoint' $GITHUB_EVENT_PATH)
          echo ::add-mask::$ENDPOINT
  run:
    needs: [censor]
    # We use a delegate action here to make sure that we do not pass in any org secrets
    uses: neoforged/action-runner/.github/workflows/run_delegate.yml@main
    with:
      endpoint: ${{ inputs.endpoint }}
      os: ${{ inputs.os }}