name: Run PR

on:
    workflow_dispatch:
        inputs:
            endpoint:
                required: true
                type: string
                description: WebSocket endpoint
            os:
                required: true
                type: string
                description: The OS to run on

jobs:
    run:
        uses: neoforged/practionrunner/.github/workflows/run_pr_delegate.yml@main
        with:
            endpoint: ${{ inputs.endpoint }}
            os: ${{ inputs.os }}