name: Run PR
run-name: ${{ inputs.name }}

on:
    workflow_dispatch:
        inputs:
            endpoint:
                required: true
                type: string
                description: WebSocket endpoint
            os:
                required: true
                type: string
                description: The OS to run on
            name:
                required: false
                type: string
                description: The run name
                default: Run PR

jobs:
    run:
        uses: neoforged/practionrunner/.github/workflows/run_pr_delegate.yml@main
        with:
            endpoint: ${{ inputs.endpoint }}
            os: ${{ inputs.os }}